---
- name: Install and Configure DNS Clients
  hosts: dns_clients
  become: yes

  vars:
    dns_servers:
      - 192.168.161.17
      - 192.168.161.18
    domain_search: ziyotek1.local

  tasks:
    - name: Install Bind Utilities
      yum:
        name: bind-utils
        state: latest

    - name: Configure DNS Servers
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

#    - name: Restart Network Service
#      service:
#        name: network
#        state: restarted

#    - name: Restart NetworkManager Service
#      service:
#        name: NetworkManager
#        state: restarted
