---
- name: Install and Configure Chrony Clients
  hosts: chrony_clients
  become: yes

  vars:
    ntp_servers:
      - 192.168.161.15
      - 192.168.161.16

  tasks:
    - name: Install Chrony
      yum:
        name: chrony
        state: latest
      when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '8'

    - name: Enable and Start Chrony Service
      systemd:
        name: chronyd
        enabled: yes
        state: started
      when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '8'

    - name: Configure Chrony Servers
      copy:
        src: chrony_clients.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '8'

    - name: Restart Chrony Service
      systemd:
        name: chronyd
        state: restarted
      when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '8'
